version: '3.8'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - /app/.venv
    env_file:
      - .env
    environment:
      - ENVIRONMENT=development
    depends_on:
      - postgres
      - redis
    restart: unless-stopped
    networks:
      - virtual-assistant-network

  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: virtual_assistant
      POSTGRES_USER: assistant
      POSTGRES_PASSWORD: password123
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - virtual-assistant-network
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - virtual-assistant-network
    restart: unless-stopped

  celery:
    build: .
    command: celery -A app.worker.celery worker --loglevel=info
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - redis
      - postgres
    networks:
      - virtual-assistant-network
    restart: unless-stopped

  celery-beat:
    build: .
    command: celery -A app.worker.celery beat --loglevel=info
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - redis
      - postgres
    networks:
      - virtual-assistant-network
    restart: unless-stopped

volumes:
  postgres_data:
  redis_data:

networks:
  virtual-assistant-network:
    driver: bridge